var cars = {
    honda: {
        vezel2019: {
            brand: "Honda",
            model: "Vezel",
            year: "2019",
            distanceTravelled: "13,713 km",
            fuelType: "hybrid",
            transmission: "automatic",
            color: "white",
            enginCapacity: "1500cc",
            bodyType: "crossover",
            pricePKR: "85 lacs",
            imageSrc: "images/honda-vezel-hybrid-z-2019.webp",
            nameDescription: "Honda Vezel Hybrid Z 2019"

        },
        civic2013: {
            brand: "Honda",
            model: "Civic",
            year: "2013",
            distanceTravelled: "83,180 km",
            fuelType: "petrol",
            transmission: "automatic",
            color: "urban titanium",
            enginCapacity: "1800cc",
            bodyType: "sedan",
            pricePKR: "28 lacs",
            imageSrc: "images/honda-civic-vti-1-8-i-vtec-oriel-prosmatec-2013-93337152.webp",
            nameDescription: "Honda Civic VTi Oriel Prosmatec 1.8 i-VTEC 2013"
        },
        fitAria2006: {
            brand: "Honda",
            model: "Fit Aria",
            year: "2006",
            distanceTravelled: "247,604 km",
            fuelType: "petrol",
            transmission: "automatic",
            color: "black",
            enginCapacity: "1500cc",
            bodyType: "sedan",
            pricePKR: "15.8 lacs",
            imageSrc: "images/honda-city-i-dsi-vario-2006-94498970.webp",
            nameDescription: "Honda Fit Aria 1.5C 2006"
        },
        city2016: {
            brand: "Honda",
            model: "City",
            year: "2016",
            distanceTravelled: "108,567 km",
            fuelType: "petrol",
            transmission: "automatic",
            color: "taffeta white",
            enginCapacity: "1500cc",
            bodyType: "sedan",
            pricePKR: "36 lacs",
            imageSrc: "images/honda-city-aspire-prosmatec-2016-93996363.webp",
            nameDescription: "Honda City Aspire Prosmatec 1.5 i-VTEC 2016"
        },
        civic2008: {
            brand: "Honda",
            model: "Civic",
            year: "2008",
            distanceTravelled: "142,216 km",
            fuelType: "petrol",
            transmission: "manual",
            color: "crystal black",
            enginCapacity: "1800cc",
            bodyType: "sedan",
            pricePKR: "29 lacs",
            imageSrc: "images/honda-civic-vti-1-8-i-vtec-oriel-2008-92373724.webp",
            nameDescription: "Honda Civic VTi Oriel 1.8 i-VTEC 2008"
        },
        vezel2018 : {
            brand: "Honda",
            model: "Vezel",
            year: "2018",
            distanceTravelled: "62,404 km",
            fuelType: "petrol",
            transmission: "automatic",
            color: "silver",
            enginCapacity: "1500cc",
            bodyType: "crossover",
            pricePKR: "75 lacs",
            imageSrc: "images/honda-vezel-hybird-xl-2018-94261403.webp",
            nameDescription: "Honda Vezel Hybrid X L Package 2018"
        },
        accord2005 : {
            brand: "Honda",
            model: "Accord",
            year: "2005",
            distanceTravelled: "200,000 km",
            fuelType: "petrol",
            transmission: "automatic",
            color: "alabaster silver",
            enginCapacity: "2400cc",
            bodyType: "sedan",
            pricePKR: "24.5 lacs",
            imageSrc: "images/honda-accord-2-4-i-vtec-prosmatec-2005-94837097.webp",
            nameDescription: "Honda Accord VTi 2.4 2005"
        },
        city2014 : {
            brand: "Honda",
            model: "City",
            year: "2014",
            distanceTravelled: "104,000 km",
            fuelType: "petrol",
            transmission: "manual",
            color: "crystal black pearl",
            enginCapacity: "1300cc",
            bodyType: "sedan",
            pricePKR: "24.7 lacs",
            imageSrc: "images/honda-city-i-vtec-2-2014-94836903.webp",
            nameDescription: "Honda City 1.3 i-VTEC 2014"
        },
        accrod2024 : {
            brand: "Honda",
            model: "Accord",
            year: "2024",
            distanceTravelled: "1",
            fuelType: "petrol",
            transmission: "automatic",
            color: "crystal black pearl",
            enginCapacity: "1500cc",
            bodyType: "sedan",
            pricePKR: "2.31 crore",
            imageSrc: "images/honda-accord-1-5l-vtec-turbo-2024-94837009.webp",
            nameDescription: "Honda Accord 1.5L VTEC Turbo 2024"
        },
        nWgn : {
            brand: "Honda",
            model: "N Wgn",
            year: "2022",
            distanceTravelled: "5,000 km",
            fuelType: "petrol",
            transmission: "automatic",
            color: "beige",
            enginCapacity: "660cc",
            bodyType: "hatchback",
            pricePKR: "37 lacs",
            imageSrc: "images/honda-n-wgn-g-a-package-2022-93252296.webp",
            nameDescription: "Honda N Wgn G A Package 2022"
        }
    }
}
